### ISSUE TITLE
main.py is broken

### ISSUE THREAD

**Issue by craigboman** [Miamiohlibs/worldcat#2]
>>> results = main(passwd, 'swdep-min.sql')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dude/Documents/projects/worldcat/main.py", line 15, in main
    sqlName = sqlImport(sqlName)
  File "/home/dude/Documents/projects/worldcat/python/utilities.py", line 6, in sqlImport
    with open('sql/'+sqlName, 'r', encoding='utf-8-sig') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sql/sql/swdep-min.sql'

**Comment by craigboman** [comment]
not sure why the concat of sqlName is duplicating 'sql/sql/swdep-min.sql' in filepath.

**Comment by craigboman** [comment]
Ran in interactive python, this does not seem to be an error at all.

**Comment by craigboman** [comment]
Issue fix not needed. User error.
